# Generated by Django 6.0.6 on 2026-07-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['name']},
        ),
    ]
