"""Tests for the feedback domain and API."""
from django.contrib.auth import get_user_model
from django.test import TestCase
from rest_framework.test import APIClient

from accounts.models import Organization
from .models import Board, Post, Vote

User = get_user_model()


class VoteModelTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user(email="a@example.com", password="pw12345!")
        self.org = Organization.objects.create(name="Acme", owner=self.user)
        self.board = Board.objects.create(organization=self.org, name="Features")
        self.post = Post.objects.create(board=self.board, author=self.user, title="Dark mode")

    def test_vote_count_reflects_votes(self):
        self.assertEqual(self.post.vote_count, 0)
        Vote.objects.create(post=self.post, user=self.user)
        self.assertEqual(self.post.vote_count, 1)

    def test_one_vote_per_user_per_post(self):
        Vote.objects.create(post=self.post, user=self.user)
        with self.assertRaises(Exception):
            Vote.objects.create(post=self.post, user=self.user)

    def test_board_slug_autogenerated(self):
        board = Board.objects.create(organization=self.org, name="Bug Reports")
        self.assertEqual(board.slug, "bug-reports")


class PostAPITests(TestCase):
    def setUp(self):
        self.client = APIClient()
        self.user = User.objects.create_user(email="b@example.com", password="pw12345!")
        self.org = Organization.objects.create(name="Acme", owner=self.user)
        self.board = Board.objects.create(organization=self.org, name="Features")
        self.post = Post.objects.create(board=self.board, author=self.user, title="Dark mode")

    def test_list_posts_is_public(self):
        response = self.client.get("/api/posts/")
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.data["count"], 1)

    def test_vote_requires_authentication(self):
        response = self.client.post(f"/api/posts/{self.post.id}/vote/")
        self.assertIn(response.status_code, (401, 403))

    def test_vote_toggles(self):
        self.client.force_authenticate(self.user)
        r1 = self.client.post(f"/api/posts/{self.post.id}/vote/")
        self.assertEqual(r1.data, {"voted": True, "vote_count": 1})
        r2 = self.client.post(f"/api/posts/{self.post.id}/vote/")
        self.assertEqual(r2.data, {"voted": False, "vote_count": 0})

    def test_create_post_sets_author(self):
        self.client.force_authenticate(self.user)
        response = self.client.post(
            "/api/posts/", {"board": self.board.id, "title": "Slack integration"}
        )
        self.assertEqual(response.status_code, 201)
        self.assertEqual(response.data["author_email"], "b@example.com")
